"""empty message

Revision ID: 11adbfe25cef
Revises: 33128ac3222f
Create Date: 2018-07-07 23:22:16.967701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11adbfe25cef'
down_revision = '33128ac3222f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_order'), 'task', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_order'), table_name='task')
    op.drop_column('task', 'order')
    # ### end Alembic commands ###
