"""empty message

Revision ID: 140b69c7c499
Revises: 11adbfe25cef
Create Date: 2018-07-20 23:13:10.243019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140b69c7c499'
down_revision = '11adbfe25cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('fin_date', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('fin_order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_task_fin_date'), 'task', ['fin_date'], unique=False)
    op.create_index(op.f('ix_task_fin_order'), 'task', ['fin_order'], unique=False)
    op.drop_index('ix_task_status', table_name='task')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.create_index('ix_task_status', 'task', ['status'], unique=False)
    op.drop_index(op.f('ix_task_fin_order'), table_name='task')
    op.drop_index(op.f('ix_task_fin_date'), table_name='task')
    op.drop_column('task', 'fin_order')
    op.drop_column('task', 'fin_date')
    op.drop_column('task', 'completed')
    # ### end Alembic commands ###
