"""empty message

Revision ID: 33128ac3222f
Revises: 02a3a26edecf
Create Date: 2018-07-07 23:00:09.385020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33128ac3222f'
down_revision = '02a3a26edecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('exp', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('status', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_task_exp'), 'task', ['exp'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.drop_column('task', 'notes')
    op.drop_column('task', 'repeat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('repeat', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_exp'), table_name='task')
    op.drop_column('task', 'status')
    op.drop_column('task', 'exp')
    # ### end Alembic commands ###
